Make falling back to find the default if the file doesn't exist and no directory is specified.

diff --git a/src/2emacs b/src/2emacs
--- a/src/2emacs
+++ b/src/2emacs
@@ -7,28 +7,29 @@
 do_create=0
 [ "$1" = "-c" ] && { do_create=1; shift; }
 
+# For backwards compatibility silently ignore these
+[ "$1" = "-name" -o "$1" = "-n" ] && shift
+
 [ -n "$1" ] || { echo "2emacs what?"; exit 1; }
 
-FILE=$1
-if [ "$1" = "-name" -o "$1" = "-n" ]; then
-    [ -n "$2" ] || { echo "2emacs -name what?"; exit 1; }
-    FILE=`find -name $2 | head -n1`
-    [ -n "$FILE" ] || { echo "no file found"; exit 1; }
-fi
+FNAME=`echo $1 | cut -d: -f1`
+N=`echo $1 | awk -F: '{print $2}'`
 
-FNAME=`echo $FILE | cut -d: -f1`
-N=`echo $FILE | awk -F: '{print $2}'`
+if [ ! -f $FNAME -a $do_create -eq 0 ]; then
+    if [ `dirname $FNAME` = "." ]; then
+	FNAME=`find -name $FNAME | head -n1`
+	[ -n "$FNAME" ] || { echo "no file found"; exit 1; }
+    else
+	echo "File doesn't exist and -c not set"
+	exit 1
+    fi
+fi
 
 # The sed is for ksh
 if [ -n "$N" -a -z "`echo $N | sed 's/[0-9]*//'`" ]; then
     ARG="+$N"
 else
     unset ARG
-fi
-
-if [ ! -f $FNAME -a $do_create -eq 0 ]; then
-    echo "$FNAME does not exist and -c not the first arg"
-    exit 1
 fi
 
 # Test /tmp/emacs$UID first since you might be running an older Emacs but
